Repository sbi-dev/sbi, pull requests merged in 2020-09, with the labels that each got.

#326 FAQ for serializing with dill
  docs/docs/faq.md
  docs/docs/faq/question_03.md
Labels: documentation

#335 allow multiD x with appropriate embedding, add warning.
  CHANGELOG.md
  sbi/inference/posteriors/base_posterior.py
  sbi/user_input/user_input_checks.py
  sbi/utils/sbiutils.py
  tests/multidimensional_x_test.py
Labels: architecture, bug

#340 batch size for posterior rejection sampling.
  sbi/utils/sbiutils.py
Labels: enhancement

#345 change seeding fixture scope to function.
  tests/conftest.py
Labels: enhancement
