Repository sbi-dev/sbi, pull requests merged in 2020-05, with the labels that each got.

#147 Add contribute page
  docs/docs/contribute.md
  docs/mkdocs.yml
Labels: documentation

#154 Pass prior statistics and shapes to density estimator utils directly.
  sbi/inference/snl/snl.py
  sbi/inference/snpe/snpe_base.py
  sbi/inference/sre/sre.py
  sbi/user_input/user_input_checks.py
  sbi/utils/get_nn_models.py
  tests/linearGaussian_snl_test.py
  tests/linearGaussian_snpe_test.py
  tests/linearGaussian_sre_test.py
Labels: API changes, bug

#157 refactor torch zeros, ones and eye imports.
  sbi/inference/posteriors/sbi_posterior.py
  sbi/inference/snl/snl.py
  sbi/inference/snpe/snpe_b.py
  sbi/inference/snpe/snpe_base.py
  sbi/inference/snpe/snpe_c.py
  sbi/inference/sre/sre.py
  tests/linearGaussian_snl_test.py
  tests/linearGaussian_sre_test.py
  tests/simulator_utils_test.py
  tests/torchutils_test.py
Labels: architecture

#161 Refactor training convergence
  sbi/inference/base.py
  sbi/inference/snl/snl.py
  sbi/inference/snpe/snpe_base.py
  sbi/inference/sre/sre.py
  tests/linearGaussian_snpe_test.py
Labels: architecture

#149 Richer indication of progress in training, simulating, sampling
  examples/HH_simulator.ipynb
  sbi/inference/base.py
  sbi/inference/posteriors/sbi_posterior.py
  sbi/inference/snl/snl.py
  sbi/inference/snpe/snpe_b.py
  sbi/inference/snpe/snpe_base.py
  sbi/inference/snpe/snpe_c.py
  sbi/inference/sre/sre.py
  sbi/simulators/simutils.py
  sbi/utils/sbiutils.py
  tests/linearGaussian_snpe_test.py
Labels: API changes, documentation, enhancement

#185 Add function for calibration kernel loss to snpe base.
  sbi/inference/snpe/snpe_b.py
  sbi/inference/snpe/snpe_base.py
  sbi/inference/snpe/snpe_c.py
Labels: bug
