Repository sbi-dev/sbi, pull requests merged in 2020-03, with the labels that each got.

#65 remove binaries from lfs. use nbstripout for notebooks
  .gitattributes
  README.md
  environment.yml
  examples/NewlinearGaussian.ipynb
  examples/NewtwoMoons.ipynb
  examples/snl_mg1.ipynb
  examples/snpec_linear_Gaussian.ipynb
  examples/snpec_slcp.ipynb
  examples/snpec_twoMoons.ipynb
  examples/sre_lotkavolterra.ipynb
  setup.py
  tests/target_samples_twoMoons/samples_gt.npy
Labels: help wanted

#70 [WIP] Refactor inference
  examples/NewlinearGaussian.ipynb
  examples/NewtwoMoons.ipynb
  examples/snpec_linear_Gaussian.ipynb
  examples/snpec_slcp.ipynb
  examples/snpec_twoMoons.ipynb
  sbi/inference/__init__.py
  sbi/inference/posteriors/sbi_posterior.py
  sbi/inference/snl/__init__.py
  sbi/inference/snl/snl.py
  sbi/inference/snpe/__init__.py
  sbi/inference/snpe/snpe_a.py
  sbi/inference/snpe/snpe_b.py
  sbi/inference/snpe/snpe_base.py
  sbi/inference/snpe/snpe_c.py
  sbi/inference/sre/__init__.py
  sbi/inference/sre/sre.py
  sbi/mcmc/slice.py
  sbi/simulators/__init__.py
  sbi/simulators/linear_gaussian.py
  sbi/simulators/simutils.py
  sbi/simulators/two_moons.py
  sbi/utils/__init__.py
  sbi/utils/get_nn_models.py
  sbi/utils/logging.py
  sbi/utils/sbi.py
  sbi/utils/sbiutils.py
  sbi/utils/torchutils.py
  tests/mcmc_slice_pyro/test_slice.py
  tests/test_linearGaussian_apt.py
  tests/test_linearGaussian_snl.py
  tests/test_linearGaussian_sre.py
  tests/test_nonlinearGaussian_apt.py
  tests/test_torchutils.py
  tests/test_twoMoons_apt.py
Labels: documentation

#96 Posterior log_prob() features and tests
  sbi/inference/posteriors/sbi_posterior.py
  sbi/inference/snl/snl.py
  sbi/inference/snpe/snpe_base.py
  sbi/inference/sre/sre.py
  sbi/simulators/linear_gaussian.py
  sbi/utils/__init__.py
  sbi/utils/dkl.py
  sbi/utils/sbiutils.py
  sbi/utils/torchutils.py
  sbi/utils/utils_for_testing.py
  tests/test_linearGaussian_apt.py
  tests/test_linearGaussian_snl.py
  tests/test_linearGaussian_sre.py
  tests/test_torchutils.py
Labels: enhancement
