Repository sbi-dev/sbi, pull requests merged in 2024-08, with the labels that each got.

#1210 fix: batched mcmc reshaping
  sbi/inference/posteriors/mcmc_posterior.py
  tests/posterior_nn_test.py
Labels: bug

#1049 feat: flow matching methods
  sbi/inference/__init__.py
  sbi/inference/fmpe/__init__.py
  sbi/inference/fmpe/fmpe_base.py
  sbi/inference/posteriors/ensemble_posterior.py
  sbi/inference/snpe/snpe_base.py
  sbi/neural_nets/__init__.py
  sbi/neural_nets/density_estimators/__init__.py
  sbi/neural_nets/density_estimators/flowmatching_estimator.py
  sbi/neural_nets/factory.py
  sbi/neural_nets/flow_matcher.py
  sbi/utils/sbiutils.py
  sbi/utils/user_input_checks.py
  tests/density_estimator_test.py
  tests/embedding_net_test.py
  tests/linearGaussian_fmpe_test.py
  tests/linearGaussian_snpe_test.py
  tutorials/16_implemented_methods.ipynb
Labels: enhancement, density_estimators

#1222 Fix type annotation in class 'ConditionedPotential'.
  sbi/analysis/conditional_density.py
  sbi/inference/potentials/posterior_based_potential.py
  sbi/utils/conditional_density_utils.py
Labels: bug

#1228 fix docs links README.md
  README.md
Labels: documentation

#1225 Fix erroneous warnings about different devices
  sbi/utils/nn_utils.py
  sbi/utils/user_input_checks.py
Labels: bug

#1235 docs: refactor readme.
  README.md
  docs/docs/faq/question_01_leakage.md
  docs/docs/faq/question_02_nans.md
  docs/docs/faq/question_03_pickling_error.md
  docs/docs/faq/question_06_resume_training.md
  docs/docs/index.md
  docs/docs/tutorials/index.md
  sbi/inference/trainers/base.py
  tutorials/00_getting_started.ipynb
  tutorials/01_gaussian_amortized.ipynb
  tutorials/04_embedding_networks.ipynb
  tutorials/05_conditional_distributions.ipynb
  tutorials/18_training_interface.ipynb
  tutorials/Example_01_DecisionMakingModel.ipynb
Labels: documentation
