Repository sbi-dev/sbi, pull requests merged in 2024-03, with the labels that each got.

#980 fix #945: update guidelines, add ref to CoC.
  CONTRIBUTING.md
Labels: documentation, hackathon

#1010 Upgrade ruff to 0.3.3
  .pre-commit-config.yaml
  pyproject.toml
Labels: less-urgent, hackathon

#993 Rename types.py to avoid import clash in PyCharm
  .gitignore
  sbi/analysis/conditional_density.py
  sbi/inference/abc/smcabc.py
  sbi/inference/posteriors/base_posterior.py
  sbi/inference/posteriors/direct_posterior.py
  sbi/inference/posteriors/ensemble_posterior.py
  sbi/inference/posteriors/importance_posterior.py
  sbi/inference/posteriors/mcmc_posterior.py
  sbi/inference/posteriors/rejection_posterior.py
  sbi/inference/posteriors/vi_posterior.py
  sbi/inference/potentials/likelihood_based_potential.py
  sbi/inference/potentials/posterior_based_potential.py
  sbi/inference/potentials/ratio_based_potential.py
  sbi/inference/snle/mnle.py
  sbi/inference/snle/snle_a.py
  sbi/inference/snpe/snpe_a.py
  sbi/inference/snpe/snpe_b.py
  sbi/inference/snpe/snpe_c.py
  sbi/inference/snre/bnre.py
  sbi/inference/snre/snre_a.py
  sbi/inference/snre/snre_b.py
  sbi/inference/snre/snre_c.py
  sbi/neural_nets/density_estimators/nflows_flow.py
  sbi/neural_nets/density_estimators/zuko_flow.py
  sbi/samplers/vi/vi_divergence_optimizers.py
  sbi/samplers/vi/vi_pyro_flows.py
  sbi/samplers/vi/vi_utils.py
  sbi/sbi_types.py
  sbi/utils/kde.py
  sbi/utils/posterior_ensemble.py
  sbi/utils/restriction_estimator.py
  sbi/utils/sbiutils.py
  sbi/utils/torchutils.py
  sbi/utils/user_input_checks.py
  tests/test_utils.py
  tutorials/utils_13_diagnosis_sbc.py
Labels: bug, hackathon

#994 Move neural nets factory out of utils
  docs/docs/reference.md
  sbi/inference/snle/snle_base.py
  sbi/inference/snpe/snpe_base.py
  sbi/inference/snpe/snpe_c.py
  sbi/inference/snre/snre_base.py
  sbi/neural_nets/__init__.py
  sbi/neural_nets/factory.py
  sbi/utils/__init__.py
  sbi/utils/get_nn_models.py
  tests/embedding_net_test.py
  tests/inference_on_device_test.py
  tests/linearGaussian_snle_test.py
  tests/linearGaussian_snpe_test.py
  tests/mcmc_test.py
  tests/mnle_test.py
  tests/neural_nets_factory.py
  tests/sbiutils_test.py
  tutorials/04_density_estimators.ipynb
  tutorials/05_embedding_net.ipynb
  tutorials/14_iid_data_and_permutation_invariant_embeddings.ipynb
Labels: bug, architecture, hackathon

#1113 ruff linting hook, fix line lengths.
  .pre-commit-config.yaml
Labels: bug

#1107 Uniform and better MCMC params for the tests
  pyproject.toml
  sbi/neural_nets/density_estimators/mixed_density_estimator.py
  sbi/utils/user_input_checks.py
  tests/conftest.py
  tests/embedding_net_test.py
  tests/ensemble_test.py
  tests/inference_on_device_test.py
  tests/linearGaussian_mdn_test.py
  tests/linearGaussian_snle_test.py
  tests/linearGaussian_snpe_test.py
  tests/linearGaussian_snre_test.py
  tests/mcmc_slice_pyro/test_slice.py
  tests/mcmc_test.py
  tests/mnle_test.py
  tests/posterior_sampler_test.py
  tests/potential_test.py
  tests/save_and_load_test.py
  tests/sbc_test.py
Labels: bug, hackathon
