Repository sbi-dev/sbi, pull requests merged in 2024-02, with the labels that each got.

#936 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: documentation

#912 Allow Apple MPS as GPU device
  sbi/utils/torchutils.py
  tests/inference_on_device_test.py
  tests/torchutils_test.py
Labels: enhancement, architecture, performance

#946 FAQ: load inference pickle on CPU
  docs/docs/faq/question_05.md
Labels: documentation

#951 Pickle save for VIPosterior
  sbi/inference/posteriors/vi_posterior.py
  sbi/samplers/mcmc/slice.py
  sbi/samplers/vi/vi_divergence_optimizers.py
  sbi/samplers/vi/vi_pyro_flows.py
  sbi/samplers/vi/vi_utils.py
  sbi/types.py
  tests/vi_test.py
Labels: enhancement

#958 update code of conduct.
  CODE_OF_CONDUCT.md
Labels: documentation
