Repository sbi-dev/sbi, pull requests merged in 2024-04, with the labels that each got.

#1063 Split the github workflow in CI and CD
  .github/codecov.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/manual_test.yml
  .github/workflows/tests.yml
  pyproject.toml
Labels: enhancement, architecture, less-urgent, hackathon

#1053 Integrate PyMC samplers and clean up unsued MCMC sampler
  examples/00_HH_simulator.ipynb
  pyproject.toml
  sbi/inference/posteriors/mcmc_posterior.py
  sbi/samplers/mcmc/__init__.py
  sbi/samplers/mcmc/build_sampler.py
  sbi/samplers/mcmc/mcmc.py
  sbi/samplers/mcmc/pymc_wrapper.py
  sbi/samplers/mcmc/slice.py
  sbi/samplers/mcmc/slice_numpy.py
  tests/mcmc_slice_pyro/LICENSE.md
  tests/mcmc_slice_pyro/__init__.py
  tests/mcmc_slice_pyro/common.py
  tests/mcmc_slice_pyro/conftest.py
  tests/mcmc_slice_pyro/test_slice.py
  tests/mcmc_test.py
  tests/posterior_sampler_test.py
  tutorials/00_getting_started_flexible.ipynb
  tutorials/01_gaussian_amortized.ipynb
Labels: enhancement, hackathon

#1121 Fix 933: add progress bars to Importance Posterior
  sbi/inference/posteriors/importance_posterior.py
  sbi/samplers/importance/importance_sampling.py
  tests/linearGaussian_snle_test.py
  tests/linearGaussian_snre_test.py
Labels: enhancement

#1129 fix errors in pymc sampler implementaton
  sbi/samplers/mcmc/pymc_wrapper.py
Labels: bug
