Repository sbi-dev/sbi, pull requests merged in 2025-03, with the labels that each got.

#1423 Corrected python version in installation document (Revised)
  docs/docs/install.md
Labels: documentation

#1515 Minor fix when moving thetas from GPU to CPU
  sbi/utils/simulation_utils.py
Labels: bug, hackathon

#1497 Unify flow matching and score-based models
  sbi/diagnostics/sbc.py
  sbi/inference/__init__.py
  sbi/inference/posteriors/__init__.py
  sbi/inference/posteriors/vector_field_posterior.py
  sbi/inference/potentials/__init__.py
  sbi/inference/potentials/score_fn_iid.py
  sbi/inference/potentials/vector_field_potential.py
  sbi/inference/trainers/fmpe/fmpe.py
  sbi/inference/trainers/npse/npse.py
  sbi/inference/trainers/npse/vector_field_inference.py
  sbi/neural_nets/estimators/__init__.py
  sbi/neural_nets/estimators/base.py
  sbi/neural_nets/estimators/flowmatching_estimator.py
  sbi/neural_nets/estimators/score_estimator.py
  sbi/samplers/ode_solvers/__init__.py
  sbi/samplers/ode_solvers/base.py
  sbi/samplers/ode_solvers/ode_builder.py
  sbi/samplers/ode_solvers/zuko_ode.py
  sbi/samplers/score/diffuser.py
  sbi/samplers/score/predictors.py
  tests/density_estimator_test.py
  tests/embedding_net_test.py
  tests/linearGaussian_fmpe_test.py
  tests/linearGaussian_npse_test.py
  tests/linearGaussian_vector_field_test.py
  tests/posterior_nn_test.py
  tests/score_samplers_test.py
Labels: hackathon, score-matching-performance
